const initialEntries = [
  { date: 'YESTERDAY', title: 'A conversation I keep replaying', preview: 'I said yes before I checked in with myself.', tag: 'Boundaries', body: 'I said yes before I checked in with myself. I keep thinking about the moment I agreed, even though a part of me wanted to say no.' },
  { date: 'MON, 22', title: 'A slower kind of morning', preview: 'I felt more like myself when I let the day begin slowly.', tag: 'Rest', body: 'The morning felt different when I didn’t rush to fill every quiet moment.' },
  { date: 'FRI, 19', title: 'Something I’m looking forward to', preview: 'It was easier to feel excited once I told someone.', tag: 'Connection', body: 'I noticed I had been keeping a small bit of good news to myself.' }
];
const patterns = [
  { index: '01 / A REPEATING THREAD', title: 'You give yourself room after you speak up.', body: 'In a few reflections, you described feeling lighter after saying what you actually needed—even when the conversation felt uncomfortable.', foot: 'SEEN IN 3 REFLECTIONS · MOST RECENT YESTERDAY' },
  { index: '02 / A QUIETER SIGNAL', title: 'The small moments seem to stay with you.', body: 'A slower morning, an unhurried walk, a conversation that felt easy. Your entries return to ordinary moments when you felt most like yourself.', foot: 'SEEN IN 4 REFLECTIONS · OVER THE LAST 2 WEEKS' }
];
const state = { view: 'home', entries: loadEntries(), conversation: [], turn: 0, draft: '', busy: false, saved: false, voiceTimer: null };
const root = document.getElementById('view-root');
const escapeHtml = (value='') => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadEntries(){try{const stored=JSON.parse(localStorage.getItem('stillroom.entries'));return Array.isArray(stored)?stored:initialEntries}catch{return initialEntries}}
function storeEntries(){try{localStorage.setItem('stillroom.entries',JSON.stringify(state.entries))}catch{showToast('Saved for this visit. Browser storage is unavailable.') }}
function dateLabel(){return new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase()}
document.getElementById('today-label').textContent = dateLabel();
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));document.getElementById('top-context').textContent=state.view==='home'?'A little space to think':state.view==='entries'?'Your reflections':state.view==='patterns'?'Threads over time':'A moment for you';if(state.view==='home')renderHome();else if(state.view==='entries')renderEntries();else if(state.view==='patterns')renderPatterns();else renderConversation()}
function renderHome(){
 const recent=state.entries.slice(0,2);
 root.innerHTML=`<section class="home-grid"><div class="main-column"><div class="welcome"><div class="eyebrow">A MOMENT FOR YOU</div><h1>What's on your<br><em>mind today?</em></h1><p>No format, no pressure. Just start wherever you are.<br>We'll figure out the rest together.</p></div><div class="composer"><textarea id="thought-input" aria-label="Write what is on your mind" placeholder="I've been thinking about…" maxlength="1500">${escapeHtml(state.draft)}</textarea><div class="composer-footer"><span class="composer-hint">A sentence, a feeling, a whole story. All welcome.</span><div class="composer-actions"><button class="voice-button" id="voice-button"><span aria-hidden="true">◖</span> Speak</button><button class="begin-button" id="begin-button">Let's reflect <span aria-hidden="true">↗</span></button></div></div></div><div class="starter-prompts"><span class="starter-label">A place to begin</span><button class="prompt-chip" data-prompt="Something's been on my mind lately.">Something on my mind</button><button class="prompt-chip" data-prompt="Today felt different, and I can't quite say why.">A moment from today</button><button class="prompt-chip" data-prompt="I keep going back and forth about a decision.">A decision I'm sitting with</button></div></div><aside class="right-column"><div class="side-heading">A THREAD TO KEEP</div><div class="thread-card"><div class="thread-mark">“</div><h3>You feel more like yourself when you make room to pause.</h3><p>A small pattern from your reflections. No need to do anything with it—just something you might recognize.</p><div class="thread-meta">NOTICED ACROSS 4 MOMENTS</div></div><div class="side-divider"></div><div class="recent-title">RECENT MOMENTS</div>${recent.map(e=>`<div class="recent-entry"><span class="entry-date">${escapeHtml(e.date)}</span><div><div class="entry-preview">${escapeHtml(e.title)}</div><span class="entry-topic">${escapeHtml(e.tag)}</span></div></div>`).join('')}<button class="text-link" data-view="entries">See all reflections →</button></aside></section>`;
 const input=document.getElementById('thought-input');input.addEventListener('input',()=>state.draft=input.value);document.getElementById('begin-button').addEventListener('click',()=>startReflection(input.value));input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')startReflection(input.value)});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt;state.draft=input.value;input.focus()}));document.getElementById('voice-button').addEventListener('click',voiceDemo);document.querySelectorAll('[data-view="entries"]').forEach(b=>b.addEventListener('click',()=>navigate('entries')))
}
function renderEntries(){root.innerHTML=`<section class="page-wrap"><div class="eyebrow">YOUR PRIVATE COLLECTION</div><h1 class="page-title">Past reflections</h1><p class="page-subtitle">A place to return to what you noticed. Your words, in your own time.</p><div class="entry-list">${state.entries.length?state.entries.map((e,i)=>`<article class="entry-row"><div class="entry-row-date">${escapeHtml(e.date)}</div><div><h3>${escapeHtml(e.title)}</h3><p>${escapeHtml(e.preview||e.body||'A moment you took time to notice.')}</p></div><span class="tag">${escapeHtml(e.tag||'Reflection')}</span></article>`).join(''):'<div class="empty-state">Your first reflection can start with one honest sentence.</div>'}</div></section>`}
function renderPatterns(){root.innerHTML=`<section class="page-wrap"><div class="eyebrow">NOTICED OVER TIME</div><h1 class="page-title">Some things keep coming back.</h1><p class="page-subtitle">Not answers. Just gentle connections across the moments you’ve shared.</p><div class="pattern-intro"><p>“Sometimes a pattern is easier to see from a little distance.”</p><div class="pattern-orbit" aria-label="A diagram connecting moments"><span class="orbit-ring"></span><span class="orbit-ring two"></span><span class="orbit-center"></span><i class="orbit-node a"></i><i class="orbit-node b"></i><i class="orbit-node c"></i></div></div><div class="pattern-grid">${patterns.map(p=>`<article class="pattern-card"><div class="pattern-index">${p.index}</div><h3>${p.title}</h3><p>${p.body}</p><div class="pattern-foot">${p.foot}</div></article>`).join('')}</div><p class="page-subtitle" style="margin-top:18px;font-size:10px">Patterns are invitations to reflect, not conclusions about you.</p></section>`}
function startReflection(text){const clean=text.trim();if(!clean){document.getElementById('thought-input').focus();showToast('Start anywhere—even a few words is enough.');return}clearTimeout(state.voiceTimer);state.draft='';state.saved=false;state.turn=1;state.conversation=[{role:'user',text:clean},{role:'ai',text:makeOpening(clean)}];state.view='conversation';render()}
function makeOpening(text){const s=text.toLowerCase();if(/work|boss|meeting|deadline|project/.test(s))return 'It sounds like work is taking up a lot of space in your mind right now. What part of it feels hardest to put down?';if(/friend|partner|family|mom|dad|relationship|conversation/.test(s))return 'It sounds like this connection matters to you. When you think about it, what feeling is closest to the surface?';if(/tired|exhaust|sleep|overwhelm|too much/.test(s))return 'There’s a lot in that. If you gave yourself permission not to solve it for a moment, what would you want someone to understand?';return 'I’m here with you. Of everything you shared, what feels like the part you most want to understand a little better?'}
function renderConversation(){const firstUser=state.conversation.find(m=>m.role==='user')?.text||'';const title=state.saved?'A moment you took time to notice':state.turn===1?'Let’s stay with that.':state.turn>=2?'Something is becoming clearer.':'A moment for you';let html=`<section class="conversation-wrap"><div class="conversation-top"><button class="back-button" id="back-home">← &nbsp; Back to your space</button><span class="session-label">A REFLECTION</span></div><h1 class="conversation-title">${title}</h1><div class="conversation">`;
 state.conversation.forEach(m=>{if(m.role==='insight'){html+=`<div class="reflection-summary"><div class="summary-kicker">WHAT I’M HEARING</div><h3>${escapeHtml(m.title)}</h3><p>${escapeHtml(m.text)}</p><div class="insight-note">${escapeHtml(m.insight)}</div><div class="summary-actions"><button class="save-button" id="save-entry">Keep this reflection ↗</button><button class="quiet-button" id="keep-private">Maybe later</button></div></div>`;return}html+=`<div class="message ${m.role==='user'?'user':''}"><span class="message-mark">${m.role==='ai'?'s':'you'}</span><div><div class="message-label">${m.role==='ai'?'STILLROOM':'YOU'}</div><div class="message-copy">${escapeHtml(m.text)}</div></div></div>`});
 if(state.busy)html+=`<div class="message"><span class="message-mark">s</span><div><div class="message-label">STILLROOM</div><div class="typing" aria-label="Stillroom is thinking"><i></i><i></i><i></i></div></div></div>`;
 if(!state.saved&&state.turn<3&&!state.busy){const prompt=state.conversation.filter(m=>m.role==='ai').at(-1)?.text||'What would you like to stay with?';html+=`<div class="followup"><small>A QUESTION TO SIT WITH</small>${escapeHtml(prompt)}</div><div class="reply-area"><textarea id="reply-input" aria-label="Continue your reflection" placeholder="Take your time. What comes up?" maxlength="1000"></textarea><div class="reply-bottom"><span class="reply-note">There’s no right answer.</span><button class="reply-submit" id="reply-submit">Keep going <span aria-hidden="true">→</span></button></div></div>`}
 html+='</div></section>';root.innerHTML=html;document.getElementById('back-home').addEventListener('click',()=>navigate('home'));const reply=document.getElementById('reply-submit');if(reply){reply.addEventListener('click',()=>continueReflection(document.getElementById('reply-input').value));document.getElementById('reply-input').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')continueReflection(e.currentTarget.value)})}const save=document.getElementById('save-entry');if(save)save.addEventListener('click',saveReflection);const later=document.getElementById('keep-private');if(later)later.addEventListener('click',()=>navigate('home'))}
function continueReflection(value){const text=value.trim();if(!text){document.getElementById('reply-input').focus();return}state.conversation.push({role:'user',text});state.turn++;state.busy=true;render();setTimeout(()=>{state.busy=false;if(state.turn>=2){const original=state.conversation.find(m=>m.role==='user')?.text||'';const response=state.conversation.filter(m=>m.role==='user').at(-1)?.text||'';state.conversation.push({role:'ai',text:makeSecondQuestion(original,response)});state.conversation.push(makeInsight(original,response))}else state.conversation.push({role:'ai',text:'That makes sense. What do you think you needed in that moment, even if it was hard to ask for?' });render()},1050)}
function makeSecondQuestion(first,second){const s=(first+' '+second).toLowerCase();if(/yes|no|boundar|say|need|agree/.test(s))return 'I hear how much you were trying to hold for everyone. What might it look like to make a little room for what you need, too?';if(/tired|rest|sleep|slow|overwhelm/.test(s))return 'You’ve been carrying a lot. What’s one small thing that would feel kind to yourself today?';return 'You’re noticing something important. If you could take one thing from this moment into the rest of your day, what would you want it to be?'}
function makeInsight(first,second){const source=(first+' '+second).toLowerCase();let title='You’re beginning to hear what you need.';let summary='There’s something meaningful in the way you paused to look at this. You don’t have to turn it into a plan right now. Naming it is already a way of making space.';let insight='A thread worth keeping: you’re paying attention to the moments when your own needs get quieter.';let tag='Self-awareness';if(/yes|no|boundar|say|need|agree/.test(source)){title='A yes can hold more than one feeling.';summary='Part of you wanted to show up for someone else, and part of you needed a moment to check in with yourself. Both things can be true. Noticing that tension may be its own kind of clarity.';insight='You’ve mentioned wanting to pause before saying yes in another reflection, too.';tag='Boundaries'}else if(/work|meeting|boss|deadline|project/.test(source)){title='You’re allowed to set the work down for a moment.';summary='It sounds like you’ve been carrying this beyond the moments it asks for your attention. Noticing when it follows you is useful information—not another thing you need to fix.';insight='This echoes a recent reflection about work taking up space after hours.';tag='Work & rest'}else if(/tired|rest|sleep|slow|overwhelm/.test(source)){title='Rest sounds like a need, not a reward.';summary='You’ve been listening to the part of you asking for a softer pace. You don’t have to earn that feeling first.';insight='You’ve noticed before that slower mornings help you feel more like yourself.';tag='Rest'}return{role:'insight',title,text:summary,insight,tag,source:first,preview:second}}
function saveReflection(){const insight=state.conversation.find(m=>m.role==='insight');if(!insight)return;const entry={date:'JUST NOW',title:insight.title,preview:insight.text,tag:insight.tag,body:insight.source};state.entries.unshift(entry);state.saved=true;state.conversation.push({role:'ai',text:'I’ve kept this moment for you. You can find it whenever you want to come back to it.'});storeEntries();render();showToast('Your reflection is saved in your private space.')}
function voiceDemo(){const button=document.getElementById('voice-button');if(button.dataset.listening==='true'){clearTimeout(state.voiceTimer);button.dataset.listening='false';button.innerHTML='<span aria-hidden="true">◖</span> Speak';showToast('Voice demo stopped.');return}button.dataset.listening='true';button.innerHTML='<span aria-hidden="true">◉</span> Listening…';showToast('Voice input is a demo—no audio is recorded.');state.voiceTimer=setTimeout(()=>{const input=document.getElementById('thought-input');if(input){input.value='I keep saying yes to things before I stop to ask myself if I have the room for them.';state.draft=input.value;button.dataset.listening='false';button.innerHTML='<span aria-hidden="true">◖</span> Speak';input.focus();showToast('A sample thought is ready. Edit it or start the reflection.')}},1500)}
function navigate(view){clearTimeout(state.voiceTimer);state.view=view;render();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
function showToast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),2800)}
const about=document.getElementById('about-dialog');document.getElementById('help-button').addEventListener('click',()=>about.showModal());document.getElementById('close-about').addEventListener('click',()=>about.close());about.addEventListener('click',e=>{if(e.target===about)about.close()});
render();
